version: '3'
services:
  cloud.server:
    image: ghcr.io/denisjet/my-cloude-storage-server/my-cloude-storage-server:latest
    container_name: my-cloude-storage-server
    restart: always
    ports:
      - 7777:7777
    volumes:
      - ./.env:/my-cloude-storage-server/.env